trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build and Publish Frontend'
  steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'index.html'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'frontend'
    displayName: 'Publish Frontend Build Artifacts'

  - script: |
      #!/bin/bash

      # Slack Webhook URL
      SLACK_WEBHOOK_URL='https://hooks.slack.com/services/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'

      # Slack channel
      SLACK_CHANNEL='#semester-project'

      # Message to send
      MESSAGE='Frontend build completed successfully!'

      # Send message to Slack
      curl -X POST -H 'Content-type: application/json' --data "{\"channel\":\"$SLACK_CHANNEL\",\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK_URL
    displayName: 'Send Slack Notification'
